/// Flutter icons MarcadorTrucoIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MarcadorTrucoIcons
///      fonts:
///       - asset: fonts/MarcadorTrucoIcons.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MarcadorTrucoIcons {
  MarcadorTrucoIcons._();

  static const _kFontFam = 'MarcadorTrucoIcons';
  static const String? _kFontPkg = null;

  static const IconData clovers = IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamonds = IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearts = IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spades = IconData(0xeaaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xf01e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xf067, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xf068, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
